name: b_link
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Database
  sqflite: any
  path_provider: any
  path: any

  # Image & permissions
  image_picker: any
  permission_handler: any

  # Notifications
  flutter_local_notifications: any

  # Linking / calls
  url_launcher: any

  # Local storage (messages)
  shared_preferences: any

  # State management
  provider: any
  workmanager: any
  background_fetch: any

  # Dates / i18n
  intl: any

  # UI helpers
  flutter_slidable: any
  flutter_svg: any
  # Secure storage and crypto
  flutter_secure_storage: any
  crypto: any
  # Timezone support for scheduled notifications
  timezone: any
  flutter_native_timezone: any
  # Firebase
  firebase_core: any
  firebase_analytics: any
  cloud_firestore: any
  firebase_auth: any
  share_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/messages.txt
    - assets/logoApp.jpg
    - assets/pictureFirst.jpg
    - assets/pictureSecond.jpg
